// Filter actions
export const NAME_SEARCH_METHOD = 'NAME_SEARCH_METHOD';
export const FULL_NAME_SEARCH_METHOD = 'FULL_NAME_SEARCH_METHOD';
export const CODE_SEARCH_METHOD = 'CODE_METHOD';
export const CURRENCY_SEARCH_METHOD = 'CURRENCY_SEARCH_METHOD';
export const LANGUAGE_SEARCH_METHOD = 'LANGUAGE_SEARCH_METHOD';
export const CAPITAL_CITY_SEARCH_METHOD = 'CAPITAL_CITY_SEARCH_METHOD';
export const REGION_SEARCH_METHOD = 'REGION_SEARCH_METHOD';